# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install tcc
      - name: Install tcc
        run: |
          echo Install tcc compiler
          sudo apt-get install -y tcc

      # Install libcurl
      - name: Install libcurl
        run: |
          echo Install libcurl
          sudo apt-get install -y curl
          sudo apt-get install -y libcurl4-openssl-dev
          curl --version

      # Print compiler information
      - name: Compiler Info
        run: |
          echo Installed compilers
          clang --version
          gcc --version
          tcc -version
      # Build bootstrap LitaC
      - name: Build Bootstrap
        run: |
          echo Building bootstrap
          export set LITAC_HOME=$GITHUB_WORKSPACE
          sh $GITHUB_WORKSPACE/build_bootstrap.sh

      # Build LitaC Compiler
      - name: Build LitaC Compiler
        run: |
          echo Building LitaC Compiler
          export set LITAC_HOME=$GITHUB_WORKSPACE
          sh $GITHUB_WORKSPACE/build.sh

      # Test LitaC Compiler
      - name: Test LitaC Compiler
        run: |
          echo Testing LitaC Compiler
          export set LITAC_HOME=$GITHUB_WORKSPACE
          sh $GITHUB_WORKSPACE/build_test.sh
